baseURL: "https://happylaber.netlify.app/"
languageCode: en-us
title: HappyLaber
theme: hugo-PaperMod

#menu:
  #main: 
  #- name: "About"
  # weight: 1
  #  url : "posts/"
  #- name: "About"
  #  weight: 1
  #  url : "about/"
  
params:
    dateFormat : "2006-01-02"
    ShowRssButtonInSectionTermList: true
    ShowCodeCopyButtons: true
    ShowReadingTime: true
    ShowWordCount: true
    comments: true
    defaultTheme: dark # dark,light
    disableThemeToggle: false
    hideFooter: true
    
    
    assets:
      favicon: "1.jpg"
      favicon16x16: "1-16x16.jpg"
      favicon32x32: "1-32x32.jpg"
      apple_touch_icon: "1.jpg"
      safari_pinned_tab: "1.jpg"
    
    
    label:
      text: "Home"       
    
    
    homeInfoParams:
        Title: Welcome!
        Content: 做自己热爱,让心欢喜的事!

    
    #socialIcons:
    #- name: "qq"
    #  url: "https://qq.com"
    #- name: "bilibili"
    #  url: "https://bilibili.com"
    #- name: "youtube"
    #  url: "https://youtube.com"
    #- name: "github"
    #  url: "https://github.com"
    #ShowShareButtons: true
    #ShareButtons: ["qq","bilibili","youtube","github"]
       
       
    profileMode:
      enabled: true
      imageUrl: "1.jpg" # optional
      imageWidth: 120
      imageHeight: 120
      buttons:
      - name: "Matlab"
        url: "https://happysimple.github.io/001---MATLAB/"
      - name: "Python"
        url: "https://happysimple.github.io/002---PYTHON/"
      - name: "GMT"
        url: "https://happysimple.github.io/003---GMT/"
      - name: "Math"
        url: "https://happysimple.github.io/005---MATH/"
      - name: "Ionosphere"
        url: "https://happysimple.github.io/004---IONOSPHERE/"
      - name: "Blogs"
        url: "https://happysimple.github.io/006---BLOGS/"          
      - name: "Writing"
        url: "https://happysimple.github.io/007---WRITE/"
      - name: "Everything"
        url: "https://happysimple.github.io/999---EVERYTHING/"